[package]
org = "embedded-alerts"
name = "embedded-alerts-clients"
version = "0.1.0"
description = "Polyglot SDK clients for Embedded Alerts"
license = "MIT"
language = "polyglot"

[package.repository]
vcs = "git"
url = "https://github.com/embedded-alerts/embedded-alerts-clients"

[publish]
include_readme = true
tag_format = "v{version}"
exclude = [".env", ".env.*", "node_modules/**", "target/**", "dist/**", "*.log"]

[dependencies]
"embedded-alerts/eal-interfaces" = "^0.1.0"
